#!/usr/bin/env bash
# TODO: Use variables from .env file.
docker build --build-arg LINUX_ALPINE_VERSION=3.16 --build-arg AWS_CLI_VERSION=1.18.208 --build-arg S3CMD_VERSION=2.3.0 -f $DOCKERFILE_PATH -t $IMAGE_NAME .
